### ISSUE TITLE
Values got lost after clicking through application

### ISSUE THREAD

**Issue by henghx** [lipido/javafxwebview#3]
Hi, 
have done some minor changes to the app and found an issue while clicking through.
added a droplist to display the list of fruits you have generated.

e.g.
```
<select ng-model="fName" class="form-control"
	ng-options="fruit.name as fruit.name for fruit in fruits"></select>
```

![image](https://user-images.githubusercontent.com/25344687/27409399-e1a1cd88-5713-11e7-9f3b-11582d1952bb.png)

after selecting different fruits from the droplist suddenly all fields went blank
![image](https://user-images.githubusercontent.com/25344687/27409446-1b5bf472-5714-11e7-8941-8d6e8089094c.png)

the number of selection before all fields going blank is random, however it always happens.
anything i am missing from the guide? 
Am running it in windows just by double clicking the jar file.

Thanks.

**Comment by lipido** [comment]
Thank you for pointing out this interesting bug!

After investigation, I discovered that it was related to Java Garbage Collection. I have just pushed 72d162eb3e8cb09b80520b335a76205992a9d2c2 where a more detailed explanation can be found in the commit message.

You have to do two things:
1. Pull the source to get the changes made in `FruitsService` class.
2. Use the `getName()` in your select, instead of the `name` field of the Fruit.

**Comment by henghx** [comment]
Ok Thanks for the investigation and explanation.
